"""empty message

Revision ID: 0a5e57bd65c1
Revises: 
Create Date: 2019-12-23 23:47:37.746238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5e57bd65c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('price_per_day', sa.Float(), server_default='0.0', nullable=True))
    op.drop_column('car', 'price_per_hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('price_per_hour', sa.FLOAT(), nullable=False))
    op.drop_column('car', 'price_per_day')
    # ### end Alembic commands ###
