"""empty message

Revision ID: b1255df7df29
Revises: 0dbaf7571fb7
Create Date: 2020-01-01 18:14:35.397989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1255df7df29'
down_revision = '0dbaf7571fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('lease_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'lease_date')
    # ### end Alembic commands ###
